version: '3.8'

services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:14-alpine
    container_name: yaavs_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: yaavs_db
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    networks:
      - yaavs_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d yaavs_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Aplicación Next.js
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yaavs_app
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/yaavs_db?schema=public
      - NEXTAUTH_URL=http://localhost:3100
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:3100/api}
      - PORT=3100
      - NEXTAUTH_DEBUG=true
    ports:
      - "3100:3100"
    volumes:
      # Volumen para archivos de uploads si existen
      - uploads_data:/app/public/uploads
      # Volumen para logs
      - ./logs:/app/logs
    networks:
      - yaavs_network
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Servicio de migración de base de datos
  migrations:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yaavs_migrations
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/yaavs_db?schema=public
    command: sh -c "npx prisma migrate deploy && npx prisma db seed"
    volumes:
      - ./prisma:/app/prisma
    networks:
      - yaavs_network
    restart: "no"

volumes:
  postgres_data:
    driver: local
  uploads_data:
    driver: local

networks:
  yaavs_network:
    driver: bridge 