[build]
  command = "rm -rf node_modules && npm install && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"
  PRISMA_CLIENT_ENGINE_TYPE = "binary"
  PRISMA_CLI_QUERY_ENGINE_TYPE = "binary"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Eliminamos los redirects ya que el plugin de Next.js los maneja automáticamente 