[build]
builder = "nixpacks"
buildCommand = "npm install && npm run prisma:generate && npm run build"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicy = "on-failure"
restartPolicyMaxRetries = 10 