[build]
builder = "nixpacks"
buildCommand = "npm install && npm run prisma:generate && npm run build"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicy = "on-failure"
restartPolicyMaxRetries = 10

[deploy.healthcheck]
interval = "30s"
timeout = "30s"
retries = 3
startPeriod = "40s"

[deploy.start]
command = "node .next/standalone/server.js" 