[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicy = "on-failure"
restartPolicyMaxRetries = 10
port = 8080

[deploy.healthcheck]
interval = "60s"
timeout = "60s"
retries = 5
startPeriod = "120s"

[deploy.start]
command = "node .next/standalone/server.js"

[deploy.proxy]
port = 8080
target = "http://localhost:8080" 