[build]
builder = "nixpacks"
buildCommand = "npm run build && node scripts/setup-db.js"

[deploy]
startCommand = "node .next/standalone/server.js"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicy = "on-failure"
restartPolicyMaxRetries = 10 